### PR TITLE
fixed Issue 26

### PR DESCRIPTION
**Pull request by cloudxxx8**

### CODE REVIEW

**Comment by cloudxxx8** [comment]
@tsconn23 please help review and merge, or blackbox test cannot run normally

**Comment by tsconn23** [comment]
recheck

**Comment by tsconn23** [comment]
@JPWKU This PR can't be merged because of the support-rulesengine-Docker-Verify job which is required yet doesn't seem to be running and isn't triggered by a recheck.

**Comment by JPWKU** [comment]
@tsconn23 I adjusted the branch protection to look at the correct Docker-verify job, we are good now.  Does this also need to be fixed in california branch?

**Comment by tsconn23** [comment]
@JPWKU  Yes, I think we should change it in California as well.

**Pull request merged**
